# Generated by Django 3.0 on 2020-03-28 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodInventoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.IntegerField()),
                ('Description', models.CharField(max_length=150)),
                ('Unit', models.CharField(max_length=150)),
                ('Qty', models.IntegerField()),
                ('Expiration_Date', models.DateField(default=datetime.date.today)),
                ('Vegitarian', models.BooleanField(default=False)),
                ('Limit', models.IntegerField()),
            ],
        ),
    ]
