# Generated by Django 3.0 on 2020-03-29 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodInventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodinventorymodel',
            name='Expiration_Date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
